### ISSUE TITLE
Conda Recipe

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#53]
We should be able to distribute this with conda, which will lower the barrier for Jupyter/python users, and can be tested across platforms.

See:
 * https://conda-forge.org/docs/maintainer/adding_pkgs.html
 * https://github.com/conda-forge/typescript-feedstock/blob/main/recipe/meta.yaml
 * https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

**Comment by stevejpurves** [comment]
Love the idea!!

**Comment by stevejpurves** [comment]
Do we really mean just conda here? or conda + pip? is pip an equally viable way to distribute our package?

**Comment by stevejpurves** [comment]
This doesn't seem like a good way forward. The only viable way to distribute the npm package would be to pre-bundle the `node-modules` folder -- as this is platform and `nodejs-sdk` dependent this would fail in some cases and work in others.

There is reportedly a `post-link.sh/.bat` but I could not get this to work in the time I spent- I think maybe because the build step ends up being empty? perhaps this will work *if* we can fetch the package during build, so that a script does run at that step.

Otherwise installing to pypi is an option to explore

**Comment by stevejpurves** [comment]
Another route is to implement a tiny python package `curvenote-manager` which can take care of the local npm package install & update

**Comment by stevejpurves** [comment]
## PYPI

* https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/
* https://stackoverflow.com/questions/27950551/how-to-execute-a-safe-bash-shell-command-within-setup-py/27953695#27953695
* https://stackoverflow.com/questions/42742991/how-setup-py-install-npm-module

**Comment by stevejpurves** [comment]
This is not as simple as we imagined - and we'll probably need to do something special like have a minimal python installer app - so we are deferring this.
